ARG DISTRO_VERSION=latest

FROM ubuntu:${DISTRO_VERSION}
RUN \
    --mount=type=cache,id=apt-cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=apt-lib,target=/var/lib/apt,sharing=locked \
    --mount=type=cache,id=debconf,target=/var/cache/debconf,sharing=locked \
    set -exu \
    && apt-get update \
    && apt-get upgrade -y  \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /workspace/ \
    && addgroup -S buildsociety -g 1000 \
    && adduser -S buildsociety -G buildsociety -u 1000 \
    && chown -R buildsociety:buildsociety /workspace/
