name: Build Container and Push to GitHub Container Registry

on:

  workflow_call:
    inputs:
      os:
        description: 'Debian, Ubuntu or Alpine'
        required: true
        default: 'alpine'
        type: string
      version:
        description: 'Version of the OS'
        required: true
        default: 'latest'
        type: string
      platforms:
        description: 'CPU architectures'
        required: true
        default: 'linux/amd64,linux/arm/v7,linux/arm64'
        type: string
      disable_cache:
        description: 'Disable cache'
        required: true
        default: false
        type: boolean

  workflow_dispatch:
    inputs:
      os:
        description: 'Debian, Ubuntu or Alpine'
        required: true
        default: 'alpine'
        type: choice
        options:
        - debian
        - ubuntu
        - alpine
      version:
        description: 'Version of the OS'
        required: true
        default: 'latest'
        type: string
      platforms:
        description: 'CPU architectures'
        required: true
        default: 'linux/amd64,linux/arm/v7,linux/arm64'
        type: string
      disable_cache:
        description: 'Disable cache'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-${{ inputs.os }}
          build-args: |
            VERSION=${{ inputs.version }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ghcr.io/buildsociety/${{ github.event.repository.name }}:${{ inputs.os }}
            ghcr.io/buildsociety/${{ github.event.repository.name }}:${{ inputs.os }}-${{ inputs.version }}
            ghcr.io/buildsociety/${{ github.event.repository.name }}-${{ inputs.os }}:${{ inputs.version }}
          annotations: |
            org.opencontainers.image.title="${{ github.repository }}"
            org.opencontainers.image.description="A container from Build Society - ${{ github.repository }}"
            org.opencontainers.image.source="${{ github.server_url }}/${{ github.repository }}"
            org.opencontainers.image.revision="${{ github.sha }}"
          no-cache: ${{ inputs.disable_cache }}
          provenance: true
          sbom: true

